//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(true)]
[assembly: System.Reflection.AssemblyTitle("Microsoft.Tts.Cosmos")]
[assembly: System.Reflection.AssemblyVersion("11.0.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("11.0.0.0")]

// Generated by the MSBuild WriteCodeFragment class on 3/30/2016 08:17:26 PM.

