#pragma checksum "..\..\..\..\Controls\Acoustic\AcousticEditor.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "B282329250EF854A33EB00F50FF88A65"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Tts.UI.Controls.Acoustic;
using Microsoft.Tts.UI.Controls.Trajectory;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Microsoft.Tts.UI.Controls.Acoustic {
    
    
    /// <summary>
    /// AcousticEditor
    /// </summary>
    public partial class AcousticEditor : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 12 "..\..\..\..\Controls\Acoustic\AcousticEditor.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ColumnDefinition _midColumn;
        
        #line default
        #line hidden
        
        
        #line 25 "..\..\..\..\Controls\Acoustic\AcousticEditor.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.GridSplitter gridSplitter1;
        
        #line default
        #line hidden
        
        
        #line 26 "..\..\..\..\Controls\Acoustic\AcousticEditor.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.GridSplitter gridSplitter2;
        
        #line default
        #line hidden
        
        
        #line 28 "..\..\..\..\Controls\Acoustic\AcousticEditor.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock textBlock1;
        
        #line default
        #line hidden
        
        
        #line 40 "..\..\..\..\Controls\Acoustic\AcousticEditor.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock textBlock2;
        
        #line default
        #line hidden
        
        
        #line 52 "..\..\..\..\Controls\Acoustic\AcousticEditor.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock textBlock3;
        
        #line default
        #line hidden
        
        
        #line 65 "..\..\..\..\Controls\Acoustic\AcousticEditor.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Microsoft.Tts.UI.Controls.Trajectory.SegmentGraph _wordSegmentGraph;
        
        #line default
        #line hidden
        
        
        #line 71 "..\..\..\..\Controls\Acoustic\AcousticEditor.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Microsoft.Tts.UI.Controls.Trajectory.SegmentGraph _phoneSegmentGraph;
        
        #line default
        #line hidden
        
        
        #line 77 "..\..\..\..\Controls\Acoustic\AcousticEditor.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Microsoft.Tts.UI.Controls.Acoustic.F0Editor _f0Editor;
        
        #line default
        #line hidden
        
        
        #line 80 "..\..\..\..\Controls\Acoustic\AcousticEditor.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Microsoft.Tts.UI.Controls.Trajectory.AxisRuler _f0YAxis;
        
        #line default
        #line hidden
        
        
        #line 86 "..\..\..\..\Controls\Acoustic\AcousticEditor.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Microsoft.Tts.UI.Controls.Acoustic.GainEditor _gainEditor;
        
        #line default
        #line hidden
        
        
        #line 89 "..\..\..\..\Controls\Acoustic\AcousticEditor.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Microsoft.Tts.UI.Controls.Trajectory.AxisRuler _gainYAxis;
        
        #line default
        #line hidden
        
        
        #line 95 "..\..\..\..\Controls\Acoustic\AcousticEditor.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Microsoft.Tts.UI.Controls.Acoustic.WaveFormViewer _waveForm;
        
        #line default
        #line hidden
        
        
        #line 98 "..\..\..\..\Controls\Acoustic\AcousticEditor.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Microsoft.Tts.UI.Controls.Trajectory.AxisRuler _waveformYAxis;
        
        #line default
        #line hidden
        
        
        #line 105 "..\..\..\..\Controls\Acoustic\AcousticEditor.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Microsoft.Tts.UI.Controls.Trajectory.DurationGraph _durations;
        
        #line default
        #line hidden
        
        
        #line 108 "..\..\..\..\Controls\Acoustic\AcousticEditor.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Microsoft.Tts.UI.Controls.Trajectory.TimeAxisScrollbar _timeAxisScallbar;
        
        #line default
        #line hidden
        
        
        #line 115 "..\..\..\..\Controls\Acoustic\AcousticEditor.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Microsoft.Tts.UI.Controls.Trajectory.ZoomControl _zoomControl;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Microsoft.Tts.UI;V11.0.0.0;component/controls/acoustic/acousticeditor.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\Controls\Acoustic\AcousticEditor.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal System.Delegate _CreateDelegate(System.Type delegateType, string handler) {
            return System.Delegate.CreateDelegate(delegateType, this, handler);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this._midColumn = ((System.Windows.Controls.ColumnDefinition)(target));
            return;
            case 2:
            this.gridSplitter1 = ((System.Windows.Controls.GridSplitter)(target));
            return;
            case 3:
            this.gridSplitter2 = ((System.Windows.Controls.GridSplitter)(target));
            return;
            case 4:
            this.textBlock1 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 5:
            this.textBlock2 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 6:
            this.textBlock3 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 7:
            this._wordSegmentGraph = ((Microsoft.Tts.UI.Controls.Trajectory.SegmentGraph)(target));
            return;
            case 8:
            this._phoneSegmentGraph = ((Microsoft.Tts.UI.Controls.Trajectory.SegmentGraph)(target));
            return;
            case 9:
            this._f0Editor = ((Microsoft.Tts.UI.Controls.Acoustic.F0Editor)(target));
            return;
            case 10:
            this._f0YAxis = ((Microsoft.Tts.UI.Controls.Trajectory.AxisRuler)(target));
            return;
            case 11:
            this._gainEditor = ((Microsoft.Tts.UI.Controls.Acoustic.GainEditor)(target));
            return;
            case 12:
            this._gainYAxis = ((Microsoft.Tts.UI.Controls.Trajectory.AxisRuler)(target));
            return;
            case 13:
            this._waveForm = ((Microsoft.Tts.UI.Controls.Acoustic.WaveFormViewer)(target));
            return;
            case 14:
            this._waveformYAxis = ((Microsoft.Tts.UI.Controls.Trajectory.AxisRuler)(target));
            return;
            case 15:
            this._durations = ((Microsoft.Tts.UI.Controls.Trajectory.DurationGraph)(target));
            return;
            case 16:
            this._timeAxisScallbar = ((Microsoft.Tts.UI.Controls.Trajectory.TimeAxisScrollbar)(target));
            return;
            case 17:
            this._zoomControl = ((Microsoft.Tts.UI.Controls.Trajectory.ZoomControl)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

