#pragma checksum "..\..\..\..\Controls\Acoustic\F0Editor.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "A06ED31BB1BF01541D7BFD27B60C9A3F"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Tts.UI.Controls.Trajectory;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Microsoft.Tts.UI.Controls.Acoustic {
    
    
    /// <summary>
    /// F0Editor
    /// </summary>
    public partial class F0Editor : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 17 "..\..\..\..\Controls\Acoustic\F0Editor.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid _grid;
        
        #line default
        #line hidden
        
        
        #line 19 "..\..\..\..\Controls\Acoustic\F0Editor.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Microsoft.Tts.UI.Controls.Trajectory.TrajectoryHighlightFrame _highlightFrames;
        
        #line default
        #line hidden
        
        
        #line 22 "..\..\..\..\Controls\Acoustic\F0Editor.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Microsoft.Tts.UI.Controls.Trajectory.IntervalLinerGraph _guidelineGraph;
        
        #line default
        #line hidden
        
        
        #line 31 "..\..\..\..\Controls\Acoustic\F0Editor.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Rectangle _gridRect;
        
        #line default
        #line hidden
        
        
        #line 34 "..\..\..\..\Controls\Acoustic\F0Editor.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Microsoft.Tts.UI.Controls.Trajectory.IntervalLinerGraph _linerGraph;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Microsoft.Tts.UI;V11.0.0.0;component/controls/acoustic/f0editor.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\Controls\Acoustic\F0Editor.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal System.Delegate _CreateDelegate(System.Type delegateType, string handler) {
            return System.Delegate.CreateDelegate(delegateType, this, handler);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 11 "..\..\..\..\Controls\Acoustic\F0Editor.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.OnSelectFramesMenuItemClick);
            
            #line default
            #line hidden
            return;
            case 2:
            
            #line 13 "..\..\..\..\Controls\Acoustic\F0Editor.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.OnResetTuneMenuItemClick);
            
            #line default
            #line hidden
            return;
            case 3:
            
            #line 14 "..\..\..\..\Controls\Acoustic\F0Editor.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.OnDragSelectedMenuItemClick);
            
            #line default
            #line hidden
            return;
            case 4:
            this._grid = ((System.Windows.Controls.Grid)(target));
            return;
            case 5:
            this._highlightFrames = ((Microsoft.Tts.UI.Controls.Trajectory.TrajectoryHighlightFrame)(target));
            return;
            case 6:
            this._guidelineGraph = ((Microsoft.Tts.UI.Controls.Trajectory.IntervalLinerGraph)(target));
            return;
            case 7:
            this._gridRect = ((System.Windows.Shapes.Rectangle)(target));
            
            #line 32 "..\..\..\..\Controls\Acoustic\F0Editor.xaml"
            this._gridRect.MouseMove += new System.Windows.Input.MouseEventHandler(this.OnMouseMove);
            
            #line default
            #line hidden
            
            #line 32 "..\..\..\..\Controls\Acoustic\F0Editor.xaml"
            this._gridRect.MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.OnMouseLeftButtonDown);
            
            #line default
            #line hidden
            
            #line 32 "..\..\..\..\Controls\Acoustic\F0Editor.xaml"
            this._gridRect.MouseLeftButtonUp += new System.Windows.Input.MouseButtonEventHandler(this.OnMouseLeftButtonUp);
            
            #line default
            #line hidden
            return;
            case 8:
            this._linerGraph = ((Microsoft.Tts.UI.Controls.Trajectory.IntervalLinerGraph)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

